### ISSUE TITLE
Option to provide Firefox profile in RemoteWebDriver Capabilities

### ISSUE THREAD

**Issue by aleksz** [infradna/selenium-client-factory#1]
com.saucelabs.sauce_ondemand.driver.SauceOnDemandSPIImpl populates Capabilities only with browser, version and OS, but I can't set custom Firefox profile (and some other features). 

``` java
FirefoxProfile profile = new FirefoxProfile();
profile.setPreference("intl.accept_languages", "ru");
DesiredCapabilities capabillities = DesiredCapabilities.firefox();
capabillities.setCapability("firefox_profile", profile);
```

**Comment by rossrowe** [comment]
Hi Aleksandr, thanks for raising the issue, I'll start looking at this now.

Cheers,

Ross

**Comment by rossrowe** [comment]
Hi again, I've included a fix for this issue, you should be able to include the parameters you want included in the sauce-ondemand uri, and they will be passed to the FirefoxProfile.  

Cheers,

Ross
