### ISSUE TITLE
Allow Mouse interactions on embedded-rc-driver

### ISSUE THREAD

**Issue by nfunes** [infradna/selenium-client-factory#3]
I was wondering if the embedded-rc-driver can be tweaked so that it allows mouse interactions with WebElements like: 

WebElement myElement =driver.findElement(By.xpath("//foo"));

Actions builder = new Actions(driver);

builder.moveToElement(myElement).build().perform();

I believe it should involve changing com.saucelabs.selenium.client.embedded_rc.WebDriverFilter so that implements HasInputDevices.

Thanks,
Nicolas

**Comment by rossrowe** [comment]
Hi Nicolas, thanks for the feedback, I'll take a look into this and I'll let you know what I find.

Cheers,

Ross

**Comment by rossrowe** [comment]
Hi, sorry for taking so long to get back to you, I've just committed a fix for this issue, could you let me know if you have any issues with it?
