### ISSUE TITLE
selenium-embedded-rc-driver not compatible with selenium 2.35.0

### ISSUE THREAD

**Issue by gboucherie** [infradna/selenium-client-factory#7]
The class WebDriverFilter implements HasInputDevices that have been moved from package org.openqa.selenium to package org.openqa.selenium.interactions between version 2.34.0 and 2.35.0.
This result as a NoClassDefFoundError when lauching the test in embedded mode.

**Comment by gboucherie** [comment]
Hi, could you make a release to make this fix available ?
Thanks

**Comment by rossrowe** [comment]
Hi, I've deployed version 2.12 which includes the fix, let me know if there are any issues.

Cheers,

Ross
